stages:
  fetch_data:
    cmd: fetch_data -v -o data/raw
    deps:
    - src/cifar_100/fetch_data.py
    outs:
    - data/raw/train
    - data/raw/test
  split:
    cmd: split -v -i data/raw/train -t data/splitted/train -e 
      data/splitted/validation
    params:
    - general.seed
    - general.validation_split_ratio
    deps:
    - data/raw/train
    - src/cifar_100/split.py
    outs:
    - data/splitted/train
    - data/splitted/validation
  preprocess_cnn_train:
    cmd: preprocess_cnn -v -i data/splitted/train -o data/preprocessed/train/cnn
    deps:
    - data/splitted/train
    - src/cifar_100/dl/preprocess_cnn.py
    outs:
    - data/preprocessed/train/cnn
  preprocess_cnn_test:
    cmd: preprocess_cnn -v -i data/raw/test -o data/preprocessed/test/cnn
    deps:
    - data/raw/test
    - src/cifar_100/dl/preprocess_cnn.py
    outs:
    - data/preprocessed/test/cnn
  preprocess_cnn_validation:
    cmd: preprocess_cnn -v -i data/splitted/validation -o 
      data/preprocessed/validation/cnn
    deps:
    - data/splitted/validation
    - src/cifar_100/dl/preprocess_cnn.py
    outs:
    - data/preprocessed/validation/cnn
  train_cnn:
    cmd: train_cnn -v -t data/preprocessed/train/cnn -e 
      data/preprocessed/validation/cnn -o models
    params:
    - general.batch_size
    - train_cnn.epochs
    - train_cnn.learning_rate
    deps:
    - data/preprocessed/train/cnn
    - data/preprocessed/validation/cnn
    - src/cifar_100/dl/train_cnn.py
    outs:
    - models/cnn_model.keras
    - models/cnn_history.npy
    - dvclive/cnn/training
  evaluate_cnn:
    cmd: evaluate_cnn -v -m models/cnn_model.keras -t 
      data/preprocessed/train/cnn -e data/preprocessed/test/cnn
    params:
    - general.batch_size
    deps:
    - models/cnn_model.keras
    - data/preprocessed/train/cnn
    - data/preprocessed/test/cnn
    - src/cifar_100/dl/evaluate_cnn.py
    outs:
    - dvclive/cnn/evaluation
  preprocess_mobilenet_train:
    cmd: preprocess_mobilenet -v -i data/splitted/train -o 
      data/preprocessed/train/mobilenet
    deps:
    - data/splitted/train
    - src/cifar_100/dl/preprocess_mobilenet.py
    outs:
    - data/preprocessed/train/mobilenet
  preprocess_mobilenet_test:
    cmd: preprocess_mobilenet -v -i data/raw/test -o 
      data/preprocessed/test/mobilenet
    deps:
    - data/raw/test
    - src/cifar_100/dl/preprocess_mobilenet.py
    outs:
    - data/preprocessed/test/mobilenet
  preprocess_mobilenet_validation:
    cmd: preprocess_mobilenet -v -i data/splitted/validation -o 
      data/preprocessed/validation/mobilenet
    deps:
    - data/splitted/validation
    - src/cifar_100/dl/preprocess_mobilenet.py
    outs:
    - data/preprocessed/validation/mobilenet
  train_mobilenet:
    cmd: train_mobilenet -v -t data/preprocessed/train/mobilenet -e 
      data/preprocessed/validation/mobilenet -o models
    params:
    - general.batch_size
    - train_mobilenet.epochs
    - train_mobilenet.fine_tuning_learning_rate
    - train_mobilenet.fine_tuning_unfreezed_layer_count
    deps:
    - data/preprocessed/train/mobilenet
    - data/preprocessed/validation/mobilenet
    - src/cifar_100/dl/train_mobilenet.py
    outs:
    - models/mobilenet_model.keras
    - models/mobilenet_history.npy
    - dvclive/mobilenet/training
  evaluate_mobilenet:
    cmd: evaluate_mobilenet -v -m models/mobilenet_model.keras -t 
      data/preprocessed/train/mobilenet -e data/preprocessed/test/mobilenet
    params:
    - general.batch_size
    deps:
    - models/mobilenet_model.keras
    - data/preprocessed/train/mobilenet
    - data/preprocessed/test/mobilenet
    - src/cifar_100/dl/evaluate_mobilenet.py
    outs:
    - dvclive/mobilenet/evaluation
metrics:
- dvclive/cnn/training/metrics.json
- dvclive/cnn/evaluation/metrics.json
- dvclive/mobilenet/evaluation/metrics.json
- dvclive/mobilenet/training/feature-extraction/metrics.json
- dvclive/mobilenet/training/fine-tuning/metrics.json
plots:
- dvclive/cnn/training/plots/metrics:
    x: step
- dvclive/cnn/evaluation/plots/metrics:
    x: step
- dvclive/mobilenet/evaluation/plots/metrics:
    x: step
- dvclive/mobilenet/training/feature-extraction/plots/metrics:
    x: step
- dvclive/mobilenet/training/fine-tuning/plots/metrics:
    x: step
