stages:
  fetch_data:
    cmd: fetch_data -v -o data/raw
    outs:
    - data/raw/train
    - data/raw/test
  split:
    cmd: split -v -i data/raw/train -t data/splitted/train -e data/splitted/validation
    params:
    - general.validation_split_ratio
    deps:
    - data/raw/train
    outs:
    - data/splitted/train
    - data/splitted/validation
  train_cnn:
    cmd: train_cnn -v -t data/splitted/train -e data/splitted/validation -o models
    params:
    - general.batch_size
    - train_cnn.epochs
    deps:
    - data/splitted/train
    - data/splitted/validation
    outs:
    - models/cnn_model.keras
    - models/cnn_history.npy
  evaluate_cnn:
    cmd: evaluate_cnn -v -m models/cnn_model.keras -t data/splitted/train -e data/raw/test
    params:
    - general.batch_size
    deps:
    - models/cnn_model.keras
    - data/splitted/train
    - data/raw/test
    outs:
    - dvclive/cnn
metrics:
- dvclive/cnn/metrics.json
- dvclive/cnn/metrics.json
plots:
- dvclive/cnn/plots/metrics:
    x: step
- dvclive/cnn/plots/metrics:
    x: step
