general:
  seed: 42
  batch_size: 32
  validation_split_ratio: 0.2
train_cnn:
  epochs: 200
  learning_rate: 0.0005
train_resnet50:
  epochs: 200
  feature_extraction_learning_rate: 0.01
  fine_tuning_learning_rate: 0.00001
  fine_tuning_unfreezed_layer_count: 10
